name: Build and Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v3.66.1)'
        required: false
        default: ''
  push:
    tags:
      - 'v*'
  release:
    types: [ published ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
        
      - name: Build with Gradle
        run: ./gradlew clean build shadowJar
        
      - name: Get version
        id: get_version
        run: |
          if [[ "${{ github.event.inputs.version }}" != "" ]]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          elif [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "version=v$(./gradlew properties -q | grep "version:" | awk '{print $2}')" >> $GITHUB_OUTPUT
          fi
        
      - name: Find JAR file
        id: find_jar
        run: |
          JAR_FILE=$(find . -name "*-all.jar" -o -name "EcoSkills-*.jar" | head -1)
          if [ -z "$JAR_FILE" ]; then
            JAR_FILE=$(find build/libs -name "*.jar" | grep -v sources | head -1)
          fi
          echo "jar_file=$JAR_FILE" >> $GITHUB_OUTPUT
          echo "jar_name=$(basename $JAR_FILE)" >> $GITHUB_OUTPUT
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: EcoSkills ${{ steps.get_version.outputs.version }}
          body: |
            ## EcoSkills Release ${{ steps.get_version.outputs.version }}
            
            ### Installation
            1. Download the JAR file from the assets below
            2. Place it in your server's `plugins` folder
            3. Restart your server
            
            ### Changes
            - Built from commit ${{ github.sha }}
            
            **Full Changelog**: https://github.com/${{ github.repository }}/compare/v3.65.0...${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
          
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.find_jar.outputs.jar_file }}
          asset_name: ${{ steps.find_jar.outputs.jar_name }}
          asset_content_type: application/java-archive
